### PR TITLE
Fix set_include_path() call for epub exports

### PR DESCRIPTION
**Pull request by r-a-y**
Hi,

On our nginx set up, we were experiencing a fatal error when attempting to do an epub export:

> PHP Fatal error:  require_once(): Failed opening required 'PEAR.php' (include_path='.:/usr/share/php:/usr/share/pear:/PATH/wp-content/plugins/anthologize/templates/epub/pear_ext') in /PATH/wp-content/plugins/anthologize/templates/epub/pear_ext/Archive.php on line 38

We narrowed the problem down to `set_include_path()`, which we addressed by:
1. Setting the include path to only the `pear_ext` directory (without prepending the current include path); and by
2. Moving the `set_include_path()` call further down the file just before `require_once( 'Archive.php' )` is called.

I also tested this on a WAMP stack and this also worked, but might require additional testing on other environments.

### CODE REVIEW

**Comment by boonebgorges** [comment]
Thanks for the PR, @r-a-y. I wonder if we can just drop the use of `set_include_path()` altogether, and let relative paths do all the work. See 73fa32e. Does this work on your installation?

**Comment by r-a-y** [comment]
> Does this work on your installation?

Unfortunately, that did not work.  Got the same fatal error as the above.  I haven't delved too deep to see what might be causing the relative path issue though.

**Comment by boonebgorges** [comment]
Cool, thanks for getting back. I'll check this out in nginx to get a 
better sense of what's going on.

**Comment by boonebgorges** [comment]
Really weird. I'm testing on nginx now and it's working fine, so it must be something about the way your PHP is configured or something like that. I don't understand why the include path has to be changed. 

Moving the `set_include_path()` call is no problem, but wiping out the current include path makes me somewhat nervous, just in case any WP code tries to do anything funny after the path has been changed. So I'm wary of making the change without understand it a bit better.

I thought at first that this might be a problem with PHP not allowing overrides (see eg http://blog.calevans.com/2008/02/14/set_include_path-failing/) but this doesn't seem likely, given that `set_include_path()` does in fact work sometimes.

I'll dig a little more. If I can't find anything, I'll just accept your change and see if anything breaks :)

**Comment by r-a-y** [comment]
Yeah, I have a feeling it's to do with the PHP set up on the production 
server as I can't reproduce this locally.

I'll see what I can gather from the production environment and get back 
to you.

**Comment by r-a-y** [comment]
Commit 9fc76d0 is more safe and simply moves the `'pear_ext'` directory to the beginning in `set_include_path()`.  This fixed things for us as well.

**Comment by boonebgorges** [comment]
:+1: Thanks, @r-a-y !

**Pull request merged**
